# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from python.device import microDevice_pb2 as python_dot_device_dot_microDevice__pb2


class RPCRequestStub(object):
    """The device request service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RPCDeviceRequest = channel.unary_unary(
                '/microDevice.RPCRequest/RPCDeviceRequest',
                request_serializer=python_dot_device_dot_microDevice__pb2.DeviceMessage.SerializeToString,
                response_deserializer=python_dot_device_dot_microDevice__pb2.DeviceReply.FromString,
                )
        self.RPCDeviceRelease = channel.unary_unary(
                '/microDevice.RPCRequest/RPCDeviceRelease',
                request_serializer=python_dot_device_dot_microDevice__pb2.DeviceMessage.SerializeToString,
                response_deserializer=python_dot_device_dot_microDevice__pb2.DeviceReply.FromString,
                )
        self.RPCDeviceIsAlive = channel.unary_unary(
                '/microDevice.RPCRequest/RPCDeviceIsAlive',
                request_serializer=python_dot_device_dot_microDevice__pb2.DeviceMessage.SerializeToString,
                response_deserializer=python_dot_device_dot_microDevice__pb2.DeviceReply.FromString,
                )
        self.RPCSessionRequest = channel.unary_unary(
                '/microDevice.RPCRequest/RPCSessionRequest',
                request_serializer=python_dot_device_dot_microDevice__pb2.SessionMessage.SerializeToString,
                response_deserializer=python_dot_device_dot_microDevice__pb2.SessionMessage.FromString,
                )
        self.RPCSessionClose = channel.unary_unary(
                '/microDevice.RPCRequest/RPCSessionClose',
                request_serializer=python_dot_device_dot_microDevice__pb2.SessionMessage.SerializeToString,
                response_deserializer=python_dot_device_dot_microDevice__pb2.SessionMessage.FromString,
                )
        self.RPCDeviceRequestList = channel.unary_unary(
                '/microDevice.RPCRequest/RPCDeviceRequestList',
                request_serializer=python_dot_device_dot_microDevice__pb2.StringMessage.SerializeToString,
                response_deserializer=python_dot_device_dot_microDevice__pb2.StringMessage.FromString,
                )


class RPCRequestServicer(object):
    """The device request service.
    """

    def RPCDeviceRequest(self, request, context):
        """Send a device serial
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPCDeviceRelease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPCDeviceIsAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPCSessionRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPCSessionClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RPCDeviceRequestList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPCRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RPCDeviceRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RPCDeviceRequest,
                    request_deserializer=python_dot_device_dot_microDevice__pb2.DeviceMessage.FromString,
                    response_serializer=python_dot_device_dot_microDevice__pb2.DeviceReply.SerializeToString,
            ),
            'RPCDeviceRelease': grpc.unary_unary_rpc_method_handler(
                    servicer.RPCDeviceRelease,
                    request_deserializer=python_dot_device_dot_microDevice__pb2.DeviceMessage.FromString,
                    response_serializer=python_dot_device_dot_microDevice__pb2.DeviceReply.SerializeToString,
            ),
            'RPCDeviceIsAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.RPCDeviceIsAlive,
                    request_deserializer=python_dot_device_dot_microDevice__pb2.DeviceMessage.FromString,
                    response_serializer=python_dot_device_dot_microDevice__pb2.DeviceReply.SerializeToString,
            ),
            'RPCSessionRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RPCSessionRequest,
                    request_deserializer=python_dot_device_dot_microDevice__pb2.SessionMessage.FromString,
                    response_serializer=python_dot_device_dot_microDevice__pb2.SessionMessage.SerializeToString,
            ),
            'RPCSessionClose': grpc.unary_unary_rpc_method_handler(
                    servicer.RPCSessionClose,
                    request_deserializer=python_dot_device_dot_microDevice__pb2.SessionMessage.FromString,
                    response_serializer=python_dot_device_dot_microDevice__pb2.SessionMessage.SerializeToString,
            ),
            'RPCDeviceRequestList': grpc.unary_unary_rpc_method_handler(
                    servicer.RPCDeviceRequestList,
                    request_deserializer=python_dot_device_dot_microDevice__pb2.StringMessage.FromString,
                    response_serializer=python_dot_device_dot_microDevice__pb2.StringMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microDevice.RPCRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RPCRequest(object):
    """The device request service.
    """

    @staticmethod
    def RPCDeviceRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microDevice.RPCRequest/RPCDeviceRequest',
            python_dot_device_dot_microDevice__pb2.DeviceMessage.SerializeToString,
            python_dot_device_dot_microDevice__pb2.DeviceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RPCDeviceRelease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microDevice.RPCRequest/RPCDeviceRelease',
            python_dot_device_dot_microDevice__pb2.DeviceMessage.SerializeToString,
            python_dot_device_dot_microDevice__pb2.DeviceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RPCDeviceIsAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microDevice.RPCRequest/RPCDeviceIsAlive',
            python_dot_device_dot_microDevice__pb2.DeviceMessage.SerializeToString,
            python_dot_device_dot_microDevice__pb2.DeviceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RPCSessionRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microDevice.RPCRequest/RPCSessionRequest',
            python_dot_device_dot_microDevice__pb2.SessionMessage.SerializeToString,
            python_dot_device_dot_microDevice__pb2.SessionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RPCSessionClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microDevice.RPCRequest/RPCSessionClose',
            python_dot_device_dot_microDevice__pb2.SessionMessage.SerializeToString,
            python_dot_device_dot_microDevice__pb2.SessionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RPCDeviceRequestList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/microDevice.RPCRequest/RPCDeviceRequestList',
            python_dot_device_dot_microDevice__pb2.StringMessage.SerializeToString,
            python_dot_device_dot_microDevice__pb2.StringMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
